name: miladtech_webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/mrmostafaei/webviewx
version: 0.2.4

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  path: ^1.8.3
  pointer_interceptor: ^0.9.3+7
  uuid: ^3.0.7
  webview_flutter: ^4.4.2
  webview_flutter_platform_interface: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
